/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

/*
 * Code generated by mk-go tools/pluginbuild. DO NOT EDIT.
 *
 * plugins/ にサーバープラグインが置かれるとここが書き換わる (mk-go #2479)。
 * 既定は空なので、プラグインを使わないビルドでは何も読み込まれない。
 */

import type { PluginDefinition } from '@/plugin-api.js';

export const serverPlugins: PluginDefinition[] = [];
