/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

/*
 * Code generated by mk-go tools/pluginbuild. DO NOT EDIT.
 *
 * plugins/ にサーバープラグインが置かれるとここが書き換わる (mk-go #2479)。
 * 既定は空なので、プラグインを使わないビルドでは何も読み込まれない。
 */

import type { PluginDefinition } from '@/plugin-api.js';
import p0 from '@mkplugin/fedwatch';
import p1 from '@mkplugin/genshin';
import p2 from '@mkplugin/hsr';
import p3 from '@mkplugin/nowplaying';

export const serverPlugins: PluginDefinition[] = [p0, p1, p2, p3];
